name: leadgen-app
services:
  - name: backend
    github:
      repo: your-github-username/LinkedIn-LeadGen-Webscrape
      branch: main
      deploy_on_push: true
    source_dir: backend
    environment_slug: python
    instance_size_slug: basic-xxs
    instance_count: 1
    run_command: uvicorn main:app --host 0.0.0.0 --port $PORT
    envs:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: LINKEDIN_USERNAME
        type: SECRET
      - key: LINKEDIN_PW
        type: SECRET

  - name: frontend
    github:
      repo: your-github-username/LinkedIn-LeadGen-Webscrape
      branch: main
      deploy_on_push: true
    source_dir: frontend
    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1
    build_command: npm install && npm run build
    run_command: npm start
    envs:
      - key: REACT_APP_API_URL
        value: ${backend.HOSTNAME}
      - key: REACT_APP_ENV
        value: production

databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database
    version: "12" 